### ISSUE TITLE
Demo videos in README don't play

### ISSUE THREAD

**Issue by askerlee** [open-mmlab/Live2Diff#1]
AFAIK github doesn't support playing embedded videos in markdown files, unless the videos are uploaded to github server (on issues, discussions, etc.). If the videos are not too large, you can insert it in an issue thread, then replace the link with the uploaded link.

**Comment by LeoXing1996** [comment]
Hey @askerlee, thanks for you interest to our project and your notification. I accidentally used a link from my private repo. I have just updated the link in the README, so the video should now play correctly.
