### ISSUE TITLE
Thank you for publish the weights. Where is the scripts directory?

### ISSUE THREAD

**Issue by tensimixt** [open-mmlab/Live2Diff#3]
Thank you for publish the weights. Where is the scripts directory? Not seeing it in the github repo

**Comment by LeoXing1996** [comment]
Hey @tensimixt, download script is uploaded now. Welcome to have a try!

**Comment by tensimixt** [comment]
> Hey @tensimixt, download script is uploaded now. Welcome to have a try!

Thank you!
