### ISSUE TITLE
TypeError: unflattened_size must be tuple of ints, but found element of type Tensor at pos 0

### ISSUE THREAD

**Issue by zdyshine** [open-mmlab/Live2Diff#4]
Great job! I tried to run it but encountered the following error message
<img width="686" alt="1721635585361" src="https://github.com/user-attachments/assets/5c2f4422-b11b-4cd1-915a-d120d32475af">
Can you provide improvement suggestions？

**Comment by LeoXing1996** [comment]
Hey @zdyshine, seems you use the official MiDaS implementation instead of [this one](https://github.com/lewiji/MiDaS/tree/master) which support onnx export.
Please use this third-party implementation replace your current one.

**Comment by zdyshine** [comment]
Great, Thanks~~~
