### ISSUE TITLE
Clarification on the "CA" Module in the Codebase

### ISSUE THREAD

**Issue by onevfall** [open-mmlab/Live2Diff#5]
Thanks for your great work!

I have a couple of questions regarding the "CA" module in the code:
1. Does "CA" stand for "Channel Attention"? I couldn't find any module in the code that corresponds to a "CA" module.
2. Does this imply that the "CA" module is part of the Transformer3DModel? For instance, Because "CA" is in the "Res+SA+CA" in the paper, the CrossAttnDownBlock3DStreaming module seems to be composed of the ResnetBlock3D, Transformer3DModel, and get_motion_module in the code.
I would appreciate your clarification on these points and look forward to your response.

Thank you!

**Comment by LeoXing1996** [comment]
Hey @onevfall, "CA" means CrossAttention.  "Res+SA+CA" denotes to the original layers in UNet.

**Comment by onevfall** [comment]
Thanks for your reply! I fully understand your framework now. @LeoXing1996
