### ISSUE TITLE
NameError: name 'DPTDepthModel' is not defined

### ISSUE THREAD

**Issue by 2JAE22** [open-mmlab/Live2Diff#8]
I downloaded all the files listed in the README.md, but I still can’t find the DPTDepthModel. Should I be using the repository at "https://github.com/lewiji/MiDaS/tree/master"? I’m not sure where to find the model I need.
![image](https://github.com/user-attachments/assets/1ad99100-8043-41da-8abf-5b693b4cfe11)
<- thie is my tree

**Comment by marghovo** [comment]
Hi, have you cloned MiDas in `live2diff/MiDas`. I had an issue with DPTDepthModel and cloning MiDas separately solved it.

**Comment by 2JAE22** [comment]
> Hi, have you cloned MiDas in `live2diff/MiDas`. I had an issue with DPTDepthModel and cloning MiDas separately solved it.

yeah  thank you i solve it. i just command this line `git submodule...` <- this is a error message when i use it
